name: Go

on:
  push:
    branches: [ "Aula_1", "Aula_2", "Projeto_base" ]
  pull_request:
    branches: [ "Aula_1", "Aula_2", "Projeto_base" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root

    strategy:
      matrix:
        go_version: ['1.17', '1.18', '1.22']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go_version }}

    - name: Test
      run: go test -v ./...
 
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v main.go
