name: Go

on:
  push:
    branches: [ "Aula_1", "Aula_2", "Projeto_base" ]
  pull_request:
    branches: [ "Aula_1", "Aula_2", "Projeto_base" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root

    strategy:
      fail-fast: false
      matrix:
        go_version: ['1.18', '1.20', '1.22']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build containers
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Show containers
        run: docker ps

      - name: Wait PostgreSQL
        run: |
          echo "Waiting PostgreSQL..."
          for i in {1..30}; do
            docker exec $(docker ps -qf "ancestor=postgres") pg_isready && break
            sleep 2
          done

      - name: Show containers
        run: docker ps -a

      - name: Database logs
        run: docker compose logs postgres

      - name: Check PostgreSQL readiness
        run: |
          docker exec $(docker ps -qf "ancestor=postgres") pg_isready || true

      - name: Run tests
        run: go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v main.go
